import {
  formatLegacyAutoTitle,
  getDefaultChartTitle,
  isAutoGeneratedTitle,
} from './chartTitle';

const sampleDataset = {
  id: 'my-dataset',
  game: 'TestGame',
  startDate: '2024-01',
  endDate: '2024-02',
  featureLevel: 'player',
  OGDVersion: '1',
  source: 'api',
  data: [],
  columnTypes: {},
  supportedChartTypes: ['bar'],
  additionalDetails: { split: 'train' },
} as GameData;

describe('getDefaultChartTitle', () => {
  it('returns the dataset id for single-dataset charts', () => {
    expect(getDefaultChartTitle(['my-dataset'])).toBe('my-dataset');
  });

  it('returns a vs title for dataset comparison charts', () => {
    expect(
      getDefaultChartTitle(['dataset-a', 'dataset-b'], 'datasetComparison'),
    ).toBe('dataset-a vs dataset-b');
  });
});

describe('formatLegacyAutoTitle', () => {
  it('matches the previous auto-generated title format', () => {
    expect(formatLegacyAutoTitle(sampleDataset)).toBe(
      'TestGame 2024-01-2024-02 player train',
    );
  });
});

describe('isAutoGeneratedTitle', () => {
  const getDatasetByID = (id: string) =>
    id === 'my-dataset' ? sampleDataset : undefined;

  it('detects legacy auto titles', () => {
    expect(
      isAutoGeneratedTitle(
        'TestGame 2024-01-2024-02 player train',
        ['my-dataset'],
        'bar',
        getDatasetByID,
      ),
    ).toBe(true);
  });

  it('detects default comparison titles', () => {
    expect(
      isAutoGeneratedTitle(
        'dataset-a vs dataset-b',
        ['dataset-a', 'dataset-b'],
        'datasetComparison',
        () => undefined,
      ),
    ).toBe(true);
  });

  it('does not treat custom titles as auto-generated', () => {
    expect(
      isAutoGeneratedTitle(
        'My custom chart',
        ['my-dataset'],
        'bar',
        getDatasetByID,
      ),
    ).toBe(false);
  });
});
