import { VizTypeKey } from '../constants/vizTypes';

export function getDefaultChartTitle(
  datasetIds: string[],
  vizType?: VizTypeKey,
): string {
  if (
    vizType === 'datasetComparison' &&
    datasetIds.length >= 2 &&
    datasetIds[0] &&
    datasetIds[1]
  ) {
    return `${datasetIds[0]} vs ${datasetIds[1]}`;
  }
  return datasetIds[0] ?? '';
}

export function formatLegacyAutoTitle(dataset: GameData): string {
  return (
    `${dataset.game} ${dataset.startDate}-${dataset.endDate} ${dataset.featureLevel} ${dataset.additionalDetails?.split ?? ''}` ||
    ''
  );
}

export function isAutoGeneratedTitle(
  title: string,
  datasetIds: string[],
  vizType: VizTypeKey,
  getDatasetByID: (id: string) => GameData | undefined,
): boolean {
  if (!title) return false;
  if (title === getDefaultChartTitle(datasetIds, vizType)) return true;

  const dataset = datasetIds[0] ? getDatasetByID(datasetIds[0]) : undefined;
  return Boolean(dataset && title === formatLegacyAutoTitle(dataset));
}
